spring.application.name=crosslert-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=${BBDD_USER}
spring.datasource.password=${BBDD_PASSWORD}
alpha.vantage.api.key=${ALPHA_VANTAGE_API_KEY}