spring.application.name=crosslert-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=${BBDD_USER}
spring.datasource.password=${BBDD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
alpha.vantage.api.key=${ALPHA_VANTAGE_API_KEY}
candle.cache.max.days=3
spring.docker.compose.enabled=false